"""empty message

Revision ID: 598d8dba206d
Revises: ba8ae60fa2cd
Create Date: 2024-02-29 20:35:36.329949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598d8dba206d'
down_revision = 'ba8ae60fa2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('user_name',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
