"""empty message

Revision ID: 96ff84af6661
Revises: 598d8dba206d
Create Date: 2024-02-29 20:45:33.308127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ff84af6661'
down_revision = '598d8dba206d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=260),
               existing_nullable=False)
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=260),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=260),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=260),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.alter_column('user_name',
               existing_type=sa.String(length=260),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=260),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###
